[package]
name = "aksk"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "AK/SK with Cloud auth"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
